### ISSUE TITLE
"Save Locally" button on desktop version doesn't work.

### ISSUE THREAD

**Issue by LuigiMario79** [edave64/Doki-Doki-Dialog-Generator#35]
Whenever I press the Store Locally button on a content pack on the desktop version, nothing happenes. The pack doesn't even show up in the localrepo folder.

And yes, I uninstalled everything and did a fresh install, and the problem persists.

**Comment by edave64** [comment]
Can you run the "Doki Doki Dialog Generator.exe" in a console, try to install a pack locally and send me the text that appears in the console?

Please check for any personal information in the text before sending it. Especially your windows user directory could leak a real name.

**Comment by LuigiMario79** [comment]
Apologies for the long wait, but here's the text

receiving repo.install sub-5 https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs/femc.mwroach.edave64/index.json {
  id: 'femc.mwroach.edave64',
  name: 'FeMC (Switcheroo)',
  characters: [ 'FeMC (Switcheroo)' ],
  authors: [ 'Black Rabbit Artworks', 'MW Roach' ],
  kind: [ 'Characters' ],
  source: 'https://reddit.com/bi0ulm/',
  dddg1Path: 'https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs/femc.mwroach.edave64/index.json',
  dddg2Path: 'https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs/femc.mwroach.edave64/index.json',
  description: '<a href="https://reddit.com/bi0ulm/">Art</a> by <a href="https://reddit.com/u/blackrabbitartworks">Black Rabbit Artworks</a>, Original design by <a href="https://reddit.com/u/MWRoach">MW Roach</a>',
  preview: [
    'https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs/femc.mwroach.edave64/a.png',
    'https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs/femc.mwroach.edave64/1l.png',
    'https://edave64.github.io/Doki-Doki-Dialog-Generator-Packs/packs/femc.mwroach.edave64/1r.png'
  ],
  searchWords: []
} {
  'Black Rabbit Artworks': {
    reddit: 'blackrabbitartworks',
    patreon: 'BlackRabbitArtworks',
    deviantart: 'blackrabbitartworks',
    facebook: 'BlackRabbitArtworks'
  },
  'MW Roach': { reddit: 'MWRoach' }
}
Sending convo-error Error: Could not fetch content pack: connect ETIMEDOUT 2606:50c0:8000::153:443
    at Object.installContentPack (C:\Users\steph\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\packManager.js:84:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\steph\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\ipc-handlers\repo.js:10:3
    at async C:\Users\steph\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\ipc.js:97:17
    at async IpcMainImpl.<anonymous> (C:\Users\steph\AppData\Local\Programs\dddg-desktop-version\resources\app.asar\components\ipc.js:168:4)

**Comment by edave64** [comment]
Again, sorry for the massive delay.
I can't really make heads or tails of this message :/
"ETIMEDOUT 2606:50c0:8000::153:443" sounds like a network error, almost like it can't reach the server where the content packs are. Which doesn't make a lot of sense, since that's where it got the list of packs from in the first place

**Comment by LuigiMario79** [comment]
I made sure to check my connection, and it's still giving the error.
